
spring:
  datasource:
    url: jdbc:mysql://192.168.1.23:3306/maitao?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: maitao
    password: maitao108dev
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybaties-config.xml
  typeAliasesPackage: com.work.artwork
server:
  port: 9008
